---
name: CI

env:
  GENESIS: .github/workflows/sandbox/genesis/genesis.json

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build-contract:
    runs-on: ubuntu-latest
    steps:
      - run: |
          sudo apt-get update
          sudo apt-get install curl
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10.4'
          cache: 'pip'
      - name: install dependencies
        run: |
          make setup-venv setup
      - name: lint
        run: source venv/bin/activate ; make lint
      - name: build
        run: source venv/bin/activate ; make build
      - name: Check cache for Docker layers
        uses: satackey/action-docker-layer-caching@v0.0.11
        # Ignore the failure of a step and avoid terminating the job.
        continue-on-error: true
        with:
          key: docker-layer-caching-${{ github.workflow }}-${{ hashFiles(env.GENESIS) }}-{hash}
          restore-keys: docker-layer-caching-${{ github.workflow }}-${{ hashFiles(env.GENESIS) }}-
      - name: setup algorand sandbox
        uses: lucasvanmol/algorand-sandbox-action@v1
        with:
          config: dev
      - name: integration test
        run: |
          source venv/bin/activate
          make integration-test
